In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# y = Xw + b

In [21]:
X = np.array([[0,0],
             [1,0],
             [0,1],
             [1,1]])
Y = np.array([[0],
              [1],
              [1],
              [1]])
cross_entropy = tf.reduce_mean(-tf.reduce_sum(t * tf.log(y), reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)
correct_prediction = tf.equal(tf.to_float(tf.greater(y,0.5)),t) # y>0.5 => 1  /  y<0.5 => 0 


In [22]:
sess = tf.Session()
init = tf.global_variables_initializer()

In [23]:
sess.run(init)

In [40]:
for epoch in range(200):
    sess.run(train_step, feed_dict={
        x:X,
        t:Y
    })
    my_c_e = sess.run(cross_entropy, feed_dict={
        x:X,
        t:Y
    })
    if epoch % 10 == 0 :
        print(-my_c_e)
    

-0.007858695
-0.0077624926
-0.007668553
-0.007576905
-0.0074874125
-0.0074000442
-0.0073146634
-0.007231268
-0.0071497997
-0.007070075
-0.006992154
-0.0069159297
-0.0068413727
-0.0067683766
-0.006697001
-0.0066270186
-0.0065585366
-0.0064914767
-0.006425794
-0.006361429


In [25]:
sess.run(w)

array([[1.1104002],
       [1.1104002]], dtype=float32)

In [26]:
sess.run(y, feed_dict={
    x: X
})

array([[0.8574697],
       [0.9480847],
       [0.9480847],
       [0.9822809]], dtype=float32)

In [31]:
correct_prediction.eval(session=sess, feed_dict={
    x:X,
    t:Y
})

array([[False],
       [ True],
       [ True],
       [ True]])

In [32]:
y.eval(session=sess, feed_dict={
    x:X
})

array([[0.8574697],
       [0.9480847],
       [0.9480847],
       [0.9822809]], dtype=float32)

In [41]:
correct_prediction.eval(session=sess, feed_dict={
    x:X,
    t:Y
}) 
sess.run(correct_prediction,feed_dict{x:X, t:Y})

SyntaxError: invalid syntax (<ipython-input-41-31d49177199d>, line 5)

In [43]:
import keras

Using TensorFlow backend.


In [45]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [47]:
model = Sequential([
                    Dense(input_dim=2, units=1),
                    Activation("sigmoid")
    
                   ]

)

In [50]:
model.compile(loss="binary_crossentropy", optimizer = SGD(lr=0.1))

In [52]:
model.fit(X, Y, epochs=200, batch_size=4, verbose=1)

Epoch 1/200
4/4 [==============================] - 0s 750us/step - loss: 0.2524
Epoch 2/200
4/4 [==============================] - 0s 999us/step - loss: 0.2519
Epoch 3/200
4/4 [==============================] - 0s 500us/step - loss: 0.2514
Epoch 4/200
4/4 [==============================] - 0s 500us/step - loss: 0.2508
Epoch 5/200
4/4 [==============================] - 0s 499us/step - loss: 0.2503
Epoch 6/200
4/4 [==============================] - 0s 500us/step - loss: 0.2498
Epoch 7/200
4/4 [==============================] - 0s 500us/step - loss: 0.2492
Epoch 8/200
4/4 [==============================] - 0s 500us/step - loss: 0.2487
Epoch 9/200
4/4 [==============================] - 0s 750us/step - loss: 0.2482
Epoch 10/200
4/4 [==============================] - 0s 499us/step - loss: 0.2477
Epoch 11/200
4/4 [==============================] - 0s 500us/step - loss: 0.2471
Epoch 12/200
4/4 [==============================] - 0s 499us/step - loss: 0.2466
Epoch 13/200
4/4 [===================

Epoch 103/200
4/4 [==============================] - 0s 499us/step - loss: 0.2066
Epoch 104/200
4/4 [==============================] - 0s 749us/step - loss: 0.2062
Epoch 105/200
4/4 [==============================] - 0s 749us/step - loss: 0.2058
Epoch 106/200
4/4 [==============================] - 0s 750us/step - loss: 0.2054
Epoch 107/200
4/4 [==============================] - 0s 749us/step - loss: 0.2051
Epoch 108/200
4/4 [==============================] - 0s 499us/step - loss: 0.2047
Epoch 109/200
4/4 [==============================] - 0s 749us/step - loss: 0.2043
Epoch 110/200
4/4 [==============================] - 0s 750us/step - loss: 0.2040
Epoch 111/200
4/4 [==============================] - 0s 749us/step - loss: 0.2036
Epoch 112/200
4/4 [==============================] - 0s 499us/step - loss: 0.2032
Epoch 113/200
4/4 [==============================] - 0s 500us/step - loss: 0.2029
Epoch 114/200
4/4 [==============================] - 0s 499us/step - loss: 0.2025
Epoch 115/200
4/

In [53]:
model.fit(X, Y, epochs=200, batch_size=4, verbose=0)

In [54]:
### End of learning

In [56]:
model.predict_proba(X)

array([[0.2686025 ],
       [0.89562076],
       [0.9021427 ],
       [0.99537885]], dtype=float32)

In [57]:
## 0.5보다 큰지 작은지 해보자!

In [59]:
model.predict_classes(X)

array([[0],
       [1],
       [1],
       [1]])

In [60]:
### Example : Multiple class logistic regression

In [74]:
M = 2 #dim
K = 3 #class
n = 100
N = n*K # num of obs

In [65]:
X1 = np.random.randn(n, M) + np.array((0,10))
X2 = np.random.randn(n, M) + np.array((5,5))
X3 = np.random.randn(n, M) + np.array((10,0))

Y1 = np.array([[1,0,0] for i in range(100)])
Y2 = np.array([[0,1,0] for i in range(100)])
Y3 = np.array([[0,0,1] for i in range(100)])




X = np.concatenate((X1, X2, X3), axis=0)
Y = np.concatenate((Y1, Y2, Y3), axis=0)








In [66]:
print(X.shape, Y.shape)

(300, 2) (300, 3)


In [72]:
import matplotlib.pyplot as plt

TypeError: 'NoneType' object is not iterable

In [70]:
import matplotlib as mpl
import matplotlib.pyplot as plt

c1 = np.zeros([100])+1
c2 = np.zeros([100])+2
c3 = np.zeros([100])+3
c = np.concatenate([c1,c2,c3])
plt.scatter(X[:,0],X[:,1],alpha=0.3, c=c)

TypeError: 'NoneType' object is not iterable

In [79]:
W = tf.Variable(tf.zeros([M, K]))
b = tf.Variable(tf.zeros([K]))

x = tf.placeholder(tf.float32, shape=[None, M])
t = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.nn.softmax(tf.matmul(x, W) + b)


#cross_entropy = -tf.reduce_sum(tf.reduce_sum(t*tf.log(y), axis=1))
cross_entropy = -tf.reduce_mean(tf.reduce_sum(t*tf.log(y), axis=1))

train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

In [81]:
from sklearn.utils import shuffle
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

batch_size = 50
n_batch = 300 // batch_size #6


for epoch in range(100):
    X_, Y_ = shuffle(X, Y)
    
    for i in range(n_batch):
        start = 0 + i*batch_size
        ent = start + batch_size
        sess.run(train_step, feed_dict={
            x:X_[start:end, ] ,
            t:Y_[start:end, ]
            
        })
    





In [83]:
correct_prediction = tf.equal(tf.argmax(t, axis=1), tf.argmax(y, axis=1))

In [85]:
sess_run(correct_prediction, feed_dict={
    t=Y,
    x=X
})

SyntaxError: invalid syntax (<ipython-input-85-784cd207475d>, line 2)

In [86]:
model = Sequential()
model.add(Dense(input_dim=M, units=K))
model.add(Activation("softmax"))
model.compile(loss="categorical_crossentropy", optimizer=SGC(lr=0.1))

minibatch_size = 50
model.fit(X, Y, epochs=100, batch_size = minibatch_size, verbose=0)

TypeError: softmax() got an unexpected keyword argument 'axis'

In [ ]:
model.predict_classes(X) == argmax(Y)

In [88]:
import numpy as np
import tensorflow as tf

In [ ]:
from sklearn.utils import shuffle

In [90]:
## load data

In [92]:
from tensorflow.examples.tutorials.mnist import input_data

AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'TFE_DEVICE_PLACEMENT_EXPLICIT'

In [ ]:
mnist = input_data.read_data_sets("MNIST_data/", one_hot=TRUE)

In [ ]:
train_xdata = np.array([np.reshape(x, (28*28)) for x in mnist.train.images])

In [ ]:
test_xdata = np.array([np.reshape(x, (28*28)) for x in mnist.test.images])

In [ ]:
train_labels = mnist.train.labels
test_labels = mnist.test.labels

In [ ]:
train_xdata.shape

In [ ]:
#### accuracy
#### 